### ISSUE TITLE
Code Compilation issues with recent changes.

### ISSUE THREAD

**Issue by rangareddym** [smapiot/sample-pilet-service#3]
![Issue](https://user-images.githubusercontent.com/61223838/74809776-f77efc80-5313-11ea-85cf-a8c60afd0216.JPG)

To resolve this here I added code change 

const [, requireRef] = extractRequireRef.exec(main || '') || [] **as const;**  -> added type as Const to resolve binding errors.

**Comment by FlorianRappl** [comment]
Thanks for the info!

We will fix it right away :rocket:

**Comment by FlorianRappl** [comment]
I've updated the TypeScript version. The workspace version (3.5.x) had problems with that line. The new version (3.7.x) work fine.

Changes pushed!
