### ISSUE TITLE
The missing dep - `@graphql-tools/utils` on branch main and develop

### ISSUE THREAD

**Issue by vanpipy** [smapiot/sample-pilet-service#57]
https://github.com/smapiot/sample-pilet-service/blob/ba18be36990bbd22b11e21683128724357c822cc/src/resolvers/index.ts#L5

Here is the used dep `@graphql-tools/utils` but it is missing in the `package.json`.

**Comment by FlorianRappl** [comment]
The package is only used during development and is installed as a transitive dependency.

 See the package-lock file.

**Comment by vanpipy** [comment]
Alright, it is ok with `npm`, but not the `pnpm`. Got that.

**Comment by FlorianRappl** [comment]
Well the code base is using npm. That's in the instructions.

For consumption of the package the issue does not matter. Ideally you costume the docker image or just run the sources.
